### ISSUE TITLE
Could not get generation to house values displayed

### ISSUE THREAD

**Issue by JacoboSanchez** [reptilex/tesla-style-solar-power-card#102]
Hi
   I should have something missconfigured in my environment as produced power from the grid to the house is not shown but can not figure out why. In the attached screenshot I have all the values of the configuration. Generation is 207W and all of them are in the generation_to_house parameter. Also when there is some grid to battery power (inverter gets power from grid to keep battery between 15-16%) it is shown as a line going from generation to battery

![image](https://user-images.githubusercontent.com/11249890/151141060-4b02c635-e198-4e56-802b-6e4ba09df77c.png)

Any advice would be greatly appreciated

**Comment by reptilex** [comment]
your card configuration is probably misspelled, can you post your configurations?

**Comment by JacoboSanchez** [comment]
I created the entities card by copying the card configuration and making replaces to match the entities card syntax so the names and values shown should match the ones used in the card. I did this just to see the exact parameter name and value used, I will post them anyways:

```
type: custom:tesla-style-solar-power-card
generation_to_house: sensor.remote_generation_to_house
generation_to_grid: sensor.remote_venta
generation_to_battery_entity: sensor.remote_generation_to_battery
grid_consumption_entity: sensor.remote_compra
house_consumption_entity: sensor.remote_consumo_casa
grid_to_house_entity: sensor.remote_grid_to_house
battery_to_house_entity: sensor.remote_descarga_bateria
battery_extra_entity: sensor.remote_storage_state_of_capacity_102150268986
appliance1_consumption_entity: sensor.remote_orbis_charge_data
appliance1_extra_entity: sensor.remote_volkswagen_id_state_of_charge
grid_to_battery_entity: sensor.remote_grid_to_battery
threshold_in_k: 7
```


```
type: entities
entities:
  - entity: sensor.remote_generation_to_house
    name: generation_to_house
  - entity: sensor.remote_venta
    name: generation_to_grid
  - entity: sensor.remote_generation_to_battery
    name: generation_to_battery_entity
  - entity: sensor.remote_compra
    name: grid_consumption_entity
  - entity: sensor.remote_consumo_casa
    name: house_consumption_entity
  - entity: sensor.remote_grid_to_house
    name: grid_to_house_entity
  - entity: sensor.remote_descarga_bateria
    name: battery_to_house_entity
  - entity: sensor.remote_storage_state_of_capacity_102150268986
    name: battery_extra_entity
  - entity: sensor.remote_orbis_charge_data
    name: appliance1_consumption_entity
  - entity: sensor.remote_volkswagen_id_state_of_charge
    name: appliance1_extra_entity
  - entity: sensor.remote_grid_to_battery
    name: grid_to_battery_entity
```
