### ISSUE TITLE
Feature Request - Graph size

### ISSUE THREAD

**Issue by littlbee** [reptilex/tesla-style-solar-power-card#122]
Would be great if it could be possible to give a scale factor for the whole graph.
I'm using a 7 inch tablet with Fully Kiosk and would like this card included, but it's a bit roomy right now.

**Comment by reptilex** [comment]
Vertical/horizontal stacking does not work with my card, right?

**Comment by tomcoleman** [comment]
both vertical-stack and horizontal-stack doesnt change anything for me

```
      #################################################
      #                                               #
      #                     SOLAR                     #
      #                                               #
      #################################################
      - type: vertical-stack
        title: Solar & Power
        view_layout:
          grid-area: solar
        columns: 1
        cards:


          - type: 'custom:tesla-style-solar-power-card'


            generation_icon: 'mdi:solar-power'
            house_without_appliances_values: 1
            show_w_not_kw: 1
            #hide_inactive_lines: 1
            #change_house_bubble_color_with_flow: 1
            show_gap: true

###Grid Power###
            grid_to_house_entity: sensor.solax_apf_grid2house
            grid_to_battery_entity: sensor.solax_apf_grid2batt
###Solar Power###
            generation_to_grid_entity: sensor.solax_apf_solar2grid
            generation_to_battery_entity: sensor.solax_apf_solar2batt
            generation_to_house_entity: sensor.solax_apf_solar2house
            
###Battery Power###
            battery_to_house_entity: sensor.solax_apf_batt2house
            battery_to_grid_entity: sensor.solax_apf_batt2grid
            grid_entity: sensor.solax_measured_power
            house_entity: sensor.solax_apf_real_house_load
```
