### ISSUE TITLE
Make grid optional

### ISSUE THREAD

**Issue by enwi** [reptilex/tesla-style-solar-power-card#13]
Hey I was wondering whether you could make the grid part optional, since I have an off-grid system it does not make much sense for me to have the grid part showing?

**Comment by reptilex** [comment]
Interesting, I will check how much work that would be, but probably I can make it work. Give me a few days

**Comment by enwi** [comment]
That would be awesome, I could also give it a try, but I also have no experience with these sort of plug-ins

**Comment by enwi** [comment]
Also in that regard for small solar installations displaying the wattage as `kW` might be too large of a unit. At least for me either having an option to specify it or to make it autoscale would be really nice:
<img width="341" alt="Bildschirmfoto 2020-11-17 um 09 53 58" src="https://user-images.githubusercontent.com/25170066/99367944-de16db00-28ba-11eb-8f48-535d43bd7a44.png">

**Comment by jesserockz** [comment]
To add to this, Maybe every circle and line could be optional.
Use cases could be:
- a standalone solar battery charger (doesn't have to be apart of house power)
- a solar export only system / solar farm

Or any combination based on the entities given in the card config.

**Comment by reptilex** [comment]
That's a good feature request it means a big refactoring, hope to get it done soon. Have started.

**Comment by jesserockz** [comment]
I tried it locally but my js skill level is not high enough and I made a mess. =)
Almost needed to start again to make it all dynamic.

**Comment by reptilex** [comment]
I'm doing a complete redesign this time on typescript and with better memory and update handling, but it's going to take at least a month. Maybe christmas helps.

**Comment by reptilex** [comment]
just as an update, my test version has this running will be online in january

**Comment by reptilex** [comment]
Done in Beta. Checkout either the beta release, maybe it's already available through HACS, otherwise either as a release or from the git branch beta1.1. As soon as a few people test this it will become the main branch.

**Comment by enwi** [comment]
I am also having some issues. I am using beta1.1.2.

config:
```yaml
type: 'custom:tesla-style-solar-power-card'
show_w_not_kw: 1
solar_consumption_entity: sensor.solar_01_pl_power
solar_yield_entity: sensor.solar_01_p_power
house_consumption_entity: sensor.solar_01_l_power
battery_charge_entity: sensor.solar_01_b_charge
battery_charging_entity: sensor.solar_01_b_power
battery_consumption_entity: sensor.solar_01_bl_power
```
screenshot:
<img width="390" alt="Screenshot" src="https://user-images.githubusercontent.com/25170066/110836642-91f40a00-82a0-11eb-916f-bda76f005254.png">

**Comment by reptilex** [comment]
Well beta has new configuration variables and a different way of defining things, check the NEW Readme. Your configuration should look more like this:
```yml
type: 'custom:tesla-style-solar-power-card'
#bubbles
generation_yield_entity: sensor.solar_01_p_power
battery_consumption_entity: sensor.solar_01_bl_power
house_consumption_entity: sensor.solar_01_l_power
#lines
generation_to_house_entity: sensor.solar_01_pl_power
generation_to_battery:sensor.solar_01_b_power
#extra variables for text
battery_extra_entity: sensor.solar_01_b_charge
#other option
show_w_not_kw: 1
```

**Comment by enwi** [comment]
Thanks @reptilex I will try it

**Comment by enwi** [comment]
@reptilex It's better, but still seems wrong. In the picture I also added the current values of all entities.
<img width="788" alt="Screenshot" src="https://user-images.githubusercontent.com/25170066/110843252-59582e80-82a8-11eb-906f-329ed53cdcf8.png">

**Comment by reptilex** [comment]
Well three things: 

1. You cannot use negative values, you will have to change that one with a template. I'm still trying to figure out how I can make that possible, but it's not as easy as you would think.
2. I was missing a sensor for the flow from battery to power
3. I think you might have found a bug in that the whole lines are too far left due to the missing grid bubble.

```yml
type: 'custom:tesla-style-solar-power-card'
#bubbles
generation_yield_entity: sensor.solar_01_p_power
battery_consumption_entity: sensor.solar_01_bl_power
house_consumption_entity: sensor.solar_01_l_power
#lines
generation_to_house_entity: sensor.solar_01_pl_power
generation_to_battery: sensor.solar_01_b_power
battery_to_house: sensor.solar_01_bl_power
#extra variables for text
battery_extra_entity: sensor.solar_01_b_charge
#other options
show_w_not_kw: 1
```
