### ISSUE TITLE
Graphic looks strange

### ISSUE THREAD

**Issue by w1Ngx** [reptilex/tesla-style-solar-power-card#162]
Hi,

I successfully configured the input sources for the dashboard and the values match my solaredge app.
Now when I look at the card, it somehow looks off. Is there a way to fix this?

![Screenshot 2023-10-03 162758](https://github.com/reptilex/tesla-style-solar-power-card/assets/79746979/c5d992e6-c5cb-407d-ac60-a8fac825e4c1)

Thanks a lot for the great work!

**Comment by neotigger** [comment]
Try

card_mod:
  style: |
    ha-card {
      zoom: 1.5 !important;
      }

**Comment by pohly** [comment]
@mkanet: as you [had this working](https://github.com/reptilex/tesla-style-solar-power-card/issues/163#issue-1955772955), can you clarify where to put that `card_mod` snippet?

**Comment by mkanet** [comment]
> @mkanet: as you [had this working](https://github.com/reptilex/tesla-style-solar-power-card/issues/163#issue-1955772955), can you clarify where to put that `card_mod` snippet?

This is what mine looks like now..

```yaml
type: custom:tesla-style-solar-power-card
grid_entity: sensor.apf_grid_entity
grid_extra_entity: sensor.pge_electric_cost_to_date
house_entity: sensor.apf_real_house_load
generation_entity: sensor.apf_generation_entity
battery_entity: sensor.apf_battery_entity
grid_to_house_entity: sensor.apf_grid2house
grid_to_battery_entity: sensor.apf_grid2batt
generation_to_grid_entity: sensor.apf_solar2grid
generation_to_battery_entity: sensor.apf_solar2batt
generation_to_house_entity: sensor.apf_solar2house
battery_to_house_entity: sensor.apf_batt2house
battery_to_grid_entity: sensor.apf_batt2grid
battery_extra_entity: sensor.powerwall_charge
change_house_bubble_color_with_flow: 1
hide_inactive_lines: 1
speed_factor: 0.05
show_gap: true
card_mod:
  style: |
    ha-card {
      zoom: 1 !important;
    }
```
