### ISSUE TITLE
Help with Growatt Sensors

### ISSUE THREAD

**Issue by LanceMcCarthy** [reptilex/tesla-style-solar-power-card#169]
I've already set this card up before in one of my houses that uses a Powerwall, and it's working great! Thank you!

However, I just got a new system for a different place (where I have a 2nd Home assistant instance running), and I cannot, for the life of me, get it to work with this card.

Here is my current setup:

```yaml 
type: custom:tesla-style-solar-power-card
generation_to_grid_entity: sensor.growatt_spf_grid_energy_in
generation_to_battery_entity: sensor.growatt_spf_pv_energy
generation_to_house_entity: sensor.growatt_spf_pv_energy
grid_to_battery_entity: sensor.growatt_spf_battery_energy_out
grid_to_house_entity: sensor.growatt_spf_grid_energy_out
battery_to_house_entity: sensor.growatt_spf_battery_energy_out
grid_entity: sensor.growatt_spf_grid_power
house_entity: sensor.growatt_spf_load_power
battery_entity: sensor.growatt_spf_battery_power
generation_entity: sensor.growatt_spf_pv_power
house_without_appliances_values: 1
appliance1_consumption_entity: sensor.fridge_1_tp_link_current_consumption
appliance2_consumption_entity: sensor.fridge_2_tp_link_current_consumption
grid_icon: mdi:transmission-tower
generation_icon: mdi:solar-panel-large
house_icon: mdi:home
battery_icon: mdi:battery
appliance1_icon: mdi:fridge
appliance2_icon: mdi:fridge
```

but it's either not showing the correct values or I am not understanding what it is expecting for inputs (the latter is 99.9% more likely)
![image](https://github.com/reptilex/tesla-style-solar-power-card/assets/3520532/81da376c-dd51-4aba-ba40-182a9f4757e3)

Can you offer any guidance or documentation for Growatt inverters? They seem to be very popular, so I'm hoping something already exists. In case it doesn't, here is a list of my available sensors:

```yaml
Growatt SPF AC output frequency: sensor.growatt_spf_ac_output_frequency
Growatt SPF AC output voltage: sensor.growatt_spf_ac_output_voltage
Growatt SPF Back to battery voltage: elect.growatt_spf_back_to_battery_voltage
Growatt SPF Battery absorption charge voltage: select.growatt_spf_battery_absorption_charge_voltage
Growatt SPF Battery current: sensor.growatt_spf_battery_current
Growatt SPF Battery energy in: sensor.growatt_spf_battery_energy_in
Growatt SPF Battery energy out: sensor.growatt_spf_battery_energy_out
Growatt SPF Battery float charge voltage: select.growatt_spf_battery_float_charge_voltage
Growatt SPF Battery power: sensor.growatt_spf_battery_power
Growatt SPF Battery state of charge: sensor.growatt_spf_battery_state_of_charge
Growatt SPF Battery voltage: sensor.growatt_spf_battery_voltage
Growatt SPF Bus voltage: sensor.growatt_spf_bus_voltage
Growatt SPF Charger source priority: select.growatt_spf_charger_source_priority
Growatt SPF Device mode: sensor.growatt_spf_device_mode
Growatt SPF Grid energy in: sensor.growatt_spf_grid_energy_in
Growatt SPF Grid energy out: sensor.growatt_spf_grid_energy_out
Growatt SPF Grid frequency: sensor.growatt_spf_grid_frequency
Growatt SPF Grid power: sensor.growatt_spf_grid_power
Growatt SPF Grid voltage: sensor.growatt_spf_grid_voltage
Growatt SPF Load apparent power: sensor.growatt_spf_load_apparent_power
Growatt SPF Load energy: sensor.growatt_spf_load_energy
Growatt SPF Load percentage: sensor.growatt_spf_load_percentage
Growatt SPF Load power: sensor.growatt_spf_load_power
Growatt SPF Max charge current: number.growatt_spf_max_charge_current
Growatt SPF Max grid charge current: number.growatt_spf_max_grid_charge_current
Growatt SPF Output source priority: select.growatt_spf_output_source_priority
Growatt SPF PV current 1: sensor.growatt_spf_pv_current_1
Growatt SPF PV current 2: sensor.growatt_spf_pv_current_2
Growatt SPF PV energy: sensor.growatt_spf_pv_energy
Growatt SPF PV power: sensor.growatt_spf_pv_power
Growatt SPF PV power 1: sensor.growatt_spf_pv_power_1
Growatt SPF PV power 2: sensor.growatt_spf_pv_power_2
Growatt SPF PV voltage 1: sensor.growatt_spf_pv_voltage_1
Growatt SPF PV voltage 2: sensor.growatt_spf_pv_voltage_2
Growatt SPF Response: sensor.growatt_spf_response
Growatt SPF Shutdown battery voltage: select.growatt_spf_shutdown_battery_voltage
Growatt SPF Temperature: sensor.growatt_spf_temperature
Growatt SPF To grid battery voltage: select.growatt_spf_to_grid_battery_voltage
```

Thank you for any time and thought you put into helping out.
