### ISSUE TITLE
Using Powerwall entities

### ISSUE THREAD

**Issue by LanceMcCarthy** [reptilex/tesla-style-solar-power-card#20]
First, I just wanted to say great job with this being your 1st contribution to HA. I've been waiting for someone to do this card, kudos!

Okay, onto my problem... It is not clear which sensor goes to what attribute of your card. I've tried  several different combinations, but I'm still not able to get what I see in your demos.

### Tesla Powerwall Integration

Let's start with what I have for entities. Here is a screenshot of my integration and entity names, next to the actual live values so you can understand what they represent.

![image](https://user-images.githubusercontent.com/3520532/101061017-0ad71d80-355e-11eb-9834-439316a7c3dc.png)

### Card Configuration 

At this point, let's clarify what the entities represent. Here is my understanding of the ones we can use for your card::

- `sensor.powerwall_load_now` - The energy the house is currently using (in only)
- `sensor.powerwall_site_now` - The energy coming from the Grid (positive value is consumption, negative value is selling)
- `sensor.powerwall_solar_now` - The energy coming from my solar panels (out only)
- `sensor.powerwall_battery_now` - The energy the battery is using/providing (in and out)
- `sensor.powerwall_charge` - The battery level in %

Although I don't see a setting for it now, you could add support for:

- `binary_sensor.powerwall_charging` - string boolean representation "Charging" and Discharging"

#### How do I setup the card with those entities? 

I'm confused about the difference between the different solar attributes (yield vs consumption?) and grid settings (consumption vs feed in?)

```yaml
type: 'custom:tesla-style-solar-power-card'
house_consumption_entity: sensor.powerwall_load_now
grid_consumption_entity: ??
grid_feed_in_entity: sensor.powerwall_site_now
solar_consumption_entity: ??
solar_yield_entity: sensor.powerwall_solar_now
battery_charging_entity: sensor.powerwall_battery_now
battery_consumption_entity: sensor.powerwall_battery_now
```

Note: I do see the comments in the 2nd, larger example. The confusing part is the relationship between the consumption items and the "in" items. Do I use only the consumptions ones form the powerwall integration?

#### Custom Sensors

This leads me to my last thought, how am I supposed to get separate values for "power from" and "power to" options when I only have 1 value as a positive or negative number.

The Powerwall entities don't care about in or out, they show either a negative value or a positive value for those 4 items.

Is there an example that shows how to combine the Powerwall entities values to create those virtual sensors that will work with your card? 

### Current Setup

So that you can see where I am at right now, here is my setup:

```yaml
type: 'custom:tesla-style-solar-power-card'
house_consumption_entity: sensor.powerwall_load_now
solar_yield_entity: sensor.powerwall_solar_now
battery_charge_entity: sensor.powerwall_charge
battery_charging_entity: sensor.powerwall_battery_now
battery_consumption_entity: sensor.powerwall_battery_now
grid_consumption_entity: sensor.powerwall_site_now
```

Here's the result in Lovelace.

![image](https://user-images.githubusercontent.com/3520532/101067216-44f7ed80-3565-11eb-9584-d1738280a128.png)

Problems:

- No connection from the battery to the Grid 
- I do not have any animations

I'm pretty sure both of those problems are because of the missing "To/From" values. So again, I'm guessing this is going to rely on custom sensors to calculate the values.
