### ISSUE TITLE
Feature Request: Entity for Battery -> Grid

### ISSUE THREAD

**Issue by mdegat01** [reptilex/tesla-style-solar-power-card#38]
Tesla has an option called [ConnectedSolutions](https://www.tesla.com/connectedsolutions) for Powerwalls. When enabled you sell energy to the grid from your Powerwall during peak hours. Currently the card has no way to represent this movement of energy though, the only options for the battery are these:
```yaml
grid_to_battery_entity: sensor.grid_to_battery //expects (k)W for the power being fed from the grid to the battery (buying low cost grid price power)
battery_charge_entity: sensor.battery_charge //expects % of charge of battery
battery_charging_entity: sensor.battery_charging //expects (k)W for the power being fed from the solar panels to the battery
battery_consumption_entity: sensor.battery_consumption //expects (k)W for the power being consumed by the house from the battery
```
There would need to be a `battery_to_grid_entity` option for this so the card could then show energy moving from the battery to the grid when that entity is positive.
