### ISSUE TITLE
Testing with Tesla Powerwall

### ISSUE THREAD

**Issue by matteofranceschini** [reptilex/tesla-style-solar-power-card#49]
Hi, I'm testing the code that you published in readme.md

Placed "as is" in my configuration with a powerwall 2 it seems to work correctly for house, solar and grid, but for some unknown reason the battery is not displaying. (screenshot taken by night, running on batteries!)
<img width="333" alt="image" src="https://user-images.githubusercontent.com/3541957/113491440-2719a580-94d1-11eb-807f-11c0f77e47df.png">

I'll read more about the documentation and try to find a way to make it work ;)

BTW, I'm running HassOS on virtual machine, version 2021.3.4 :)

**Comment by reptilex** [comment]
That is very strange. You seem to be missing both battery flows. Otherwise the battery entity should be available.
Are you sure that you have both the extra 2 sensors for the battery:
```yml
    tesla_card_battery_consumption:
      unique_id: 'tesla_card_2b7aaa2588e8480aaba586815a84fcd7'
      value_template: "{{ states('sensor.powerwall_battery_now') | float | max(0) }}"
      device_class: power
      unit_of_measurement: kW
    tesla_card_battery_charging:
      unique_id: 'tesla_card_9c46447cf75942ba9ac4bcaca85ba6c5'
      value_template: "{{ states('sensor.powerwall_battery_now') | float | min(0) | abs }}"
      device_class: power
      unit_of_measurement: kW
```
And the flows for battery?
```yml
generation_to_battery_entity: sensor.tesla_card_battery_charging
battery_to_house_entity: sensor.tesla_card_battery_consumption
```
Also since the last beta I made a change that I forgot to add to the tesla config, the optional bubble entities are now like this:
```yml
house_entity: sensor.powerwall_load_now
grid_entity: sensor.tesla_card_grid_consumption
battery_entity: sensor.tesla_card_battery_consumption
generation_entity: sensor.powerwall_solar_now
``
no more consumption or yield in the middle

**Comment by matteofranceschini** [comment]
Curiously, after a few days it worked correctly. That screenshot was taken from my iphone, I had both battery flows present!

Today, for seemingly no reason, it changed to this for a while on my computer... and then got back to normal!

<img width="335" alt="image" src="https://user-images.githubusercontent.com/3541957/114182284-bf38e400-9942-11eb-9baf-d104e8e21ccb.png">

Can you suggest something I can try to help you debug this?

This is my  lovelace card:
```
type: 'custom:tesla-style-solar-power-card'
house_consumption_entity: sensor.powerwall_load_now
grid_consumption_entity: sensor.tesla_card_grid_consumption
battery_consumption_entity: sensor.tesla_card_battery_consumption
generation_yield_entity: sensor.powerwall_solar_now
generation_to_grid: sensor.tesla_card_grid_feed_in
generation_to_house_entity: sensor.tesla_card_solar_consumption
generation_to_battery_entity: sensor.tesla_card_battery_charging
battery_to_house_entity: sensor.tesla_card_battery_consumption
grid_to_house_entity: sensor.tesla_card_grid_consumption
battery_extra_entity: sensor.powerwall_charge

```

and this is what I have in my config.yaml

```
sensor:
    - platform: template
      sensors:
        tesla_card_grid_consumption:
          unique_id: 'tesla_card_5fee6ddd5c1f42a099067ce9dd44e6d1'
          value_template: "{{ states('sensor.powerwall_site_now') | float | max(0) }}"
          device_class: power
          unit_of_measurement: kW
        tesla_card_grid_feed_in:
          unique_id: 'tesla_card_52d22b847ade42c5b4526b2ff15f5aef'
          value_template: "{{ states('sensor.powerwall_site_now') | float | min(0) | abs }}"
          device_class: power
          unit_of_measurement: kW
    
        tesla_card_solar_consumption:
          unique_id: 'tesla_card_2bb67bd5264f4ec39f141f1722fea085'
          value_template: >-
            {% set solar = states('sensor.powerwall_solar_now') | float %}
            {% set house = states('sensor.powerwall_load_now') | float %}
            {{ solar if house > solar else house }}
          device_class: power
          unit_of_measurement: kW
    
        tesla_card_battery_consumption:
          unique_id: 'tesla_card_2b7aaa2588e8480aaba586815a84fcd7'
          value_template: "{{ states('sensor.powerwall_battery_now') | float | max(0) }}"
          device_class: power
          unit_of_measurement: kW
        tesla_card_battery_charging:
          unique_id: 'tesla_card_9c46447cf75942ba9ac4bcaca85ba6c5'
          value_template: "{{ states('sensor.powerwall_battery_now') | float | min(0) | abs }}"
          device_class: power
          unit_of_measurement: kW
```

I've also seen a difference between my iphone app and the browser on my computer: on the app it went like my first comment, while on my firefox browser on pc this did not happen.. but on the pc I had the anomaly in the screenshot in this post.
