### ISSUE TITLE
Extra appliances don't show their unit

### ISSUE THREAD

**Issue by shadow7412** [reptilex/tesla-style-solar-power-card#55]
Solar/Grid/Battery/House all show W (or kW), but appliances seem to just show the raw number.

![image](https://user-images.githubusercontent.com/286341/114305294-ed711c00-9b1a-11eb-8f7b-af60ff99aa6c.png)

(Sidenote, so far your powerwall sensors seem accurate, though as you can see a filter on the solar production might be needed to ignore what I assume is inverter drain. I'll know tomorrow when the sun comes up if everything is wired correctly.)

**Comment by shadow7412** [comment]
I've confirmed today that your powerwall config seems to work during the day too. I think you could safely remove that disclaimer. The only tweak I'd make is either handling or filtering out some negative values (such as from solar or grid).

**Comment by reptilex** [comment]
Hi, thanks for telling me about the powerwall. I have removed the disclaimer and it will be online with the new release.

About your issue. Are you sure your sensors for the appliances have either W or kW? Could you post your configuration and a screenshot of the appliances sensors when not 0? Thanks

**Comment by shadow7412** [comment]
Screenshot;
![image](https://user-images.githubusercontent.com/286341/115137094-39feaf00-a067-11eb-86fe-8151510ef920.png)

```yaml
type: 'custom:tesla-style-solar-power-card'
show_w_not_kw: 1
hide_inactive_lines: 1
change_house_bubble_color_with_flow: 0
energy_flow_diagramm: 1
energy_flow_diagramm_line_factor: 5
house_entity: sensor.powerwall_load_now
grid_entity: sensor.tesla_card_grid_consumption
battery_entity: sensor.tesla_card_battery_consumption
appliance1_consumption_entity: sensor.washing_machine_watts
appliance1_icon: 'mdi:washing-machine'
appliance2_consumption_entity: sensor.dryer_watts
appliance2_icon: 'mdi:television'
generation_entity: sensor.powerwall_solar_now
generation_to_grid_entity: sensor.tesla_card_grid_feed_in
generation_to_house_entity: sensor.tesla_card_solar_consumption
generation_to_battery_entity: sensor.tesla_card_battery_charging
battery_to_house_entity: sensor.tesla_card_battery_consumption
grid_to_house_entity: sensor.tesla_card_grid_consumption
battery_extra_entity: sensor.powerwall_charge
```

"Dryer" config (it's now a computer though, thus the icon change)
```yaml
dryer_watts:
      friendly_name_template: "{{ states.switch.dryer.name}} Current Consumption"
      value_template: '{{ states.switch.dryer.attributes["current_power_w"] | float }}'
      unit_of_measurement: 'W'
```

Thanks. Also that line is unnaturally thick today. I don't recall it being like that until now.

**Comment by reptilex** [comment]
Ok. I realy looked at your config 8 times now. And now I finaly get it. It's not that the unit is not showing, it's that the extra field does not hold enough space for showing it. instead of float use int and voila! You will have your watts. I had to make a cut somewhere and I actually use some sensors there that have text like "Heating" "Water" "non". So I simply thought that would be the best way.

**Comment by reptilex** [comment]
Is that the case?

**Comment by shadow7412** [comment]
I've changed the 3rd line to
```yaml
value_template: '{{ states.switch.washing_machine.attributes["current_power_w"] | int }}'
```
It doesn't seem to have made a difference. Did I interpret your instructions correctly? Also, how do you add that label you spoke about?

**Comment by reptilex** [comment]
I'm sorry but I cannot get your error in any way. If a sensor is accurate and shows a unit the unit will be used by the card explicitly. I really think your problem is you are using the definition of your sensor wrong.
From what I see you have an error in your definition of the unit and you seem to have more whitespaces than allowed. 
Try:
```yml
  dryer_watts:
    friendly_name_template: "{{ states.switch.dryer.name}} Current Consumption"
    value_template: '{{ states.switch.dryer.attributes["current_power_w"] | float }}'
    unit_of_measurement: W
```
