### ISSUE TITLE
update tesla templates

### ISSUE THREAD

**Issue by vvuk** [reptilex/tesla-style-solar-power-card#68]
The tesla templates were behaving a bit oddly in some cases; I kept seeing weird 20 watt flows between places that the app was showing nothing in.  They _might_ still be real, but they're not worth pointing out I don't think -- the code below checks the `is_active` state attribute and forces things to 0 if it's false where relevant and add a few places to clamp very small values to 0.  I also converted them to the "new style" template integration format.  (No name changes needed, the same `sensor.tesla_card_...` names remain).  It's still not perfect; it doesn't match the Tesla app in a few places, but where it doesn't I think the app is just doing more aggressive filtering (i.e. hiding even more small flows).

```
template:
    sensor:
      - name: tesla_card_grid_consumption
        unique_id: 'tesla_card_5fee6ddd5c1f42a099067ce9dd44e6d1'
        state: >-
          {% set val = states('sensor.powerwall_site_now') | float | max(0) %}
          {{ val if is_state_attr('sensor.powerwall_site_now', 'is_active', true) else 0 }}
        device_class: power
        unit_of_measurement: kW
      - name: tesla_card_grid_feed_in
        unique_id: 'tesla_card_52d22b847ade42c5b4526b2ff15f5aef'
        state: >-
          {% set val = states('sensor.powerwall_site_now') | float | min(0) | abs %}
          {{ val if val > 0.020 else 0 }}
        device_class: power
        unit_of_measurement: kW
      - name: tesla_card_solar_consumption
        unique_id: 'tesla_card_2bb67bd5264f4ec39f141f1722fea085'
        state: >-
          {% set solar = states('sensor.powerwall_solar_now') | float if is_state_attr('sensor.powerwall_solar_now', 'is_active', true) else 0 %}
          {% set house = states('sensor.powerwall_load_now') | float %}
          {{ solar if house > solar else house }}
        device_class: power
        unit_of_measurement: kW
      - name: tesla_card_battery_consumption
        unique_id: 'tesla_card_2b7aaa2588e8480aaba586815a84fcd7'
        state: "{{ states('sensor.powerwall_battery_now') | float | max(0) if is_state_attr('sensor.powerwall_battery_now', 'is_active', true) else 0 }}"
        device_class: power
        unit_of_measurement: kW
      - name: tesla_card_battery_charging
        unique_id: 'tesla_card_9c46447cf75942ba9ac4bcaca85ba6c5'
        state: "{{ states('sensor.powerwall_battery_now') | float | min(0) | abs if is_state_attr('sensor.powerwall_battery_now', 'is_active', true) else 0 }}"
        device_class: power
        unit_of_measurement: kW
```

Also a new sensor for tesla car charging consumption -- untested for when charging is _off_, as my car is currently charging :)

```
      - name: tesla_card_car_consumption
        unique_id: 'tesla_card_9c46447cf75942ba9ac4bcaca85ba6c6'
        state: "{{ states('sensor.powerwall_battery_now') | float | min(0) | abs if is_state_attr('sensor.powerwall_battery_now', 'is_active', true) else 0 }}"
        device_class: power
        unit_of_measurement: kW
        state: >-
          {% set current = state_attr('sensor.model_y_charging_rate_sensor', 'charger_actual_current') | float %}
          {% set voltage = state_attr('sensor.model_y_charging_rate_sensor', 'charger_voltage') | float %}
          {{ current * voltage / 1000.0 }}
```

I can make a PR to pull these into the README later on, if desired.
